data:
    dataset: "ChestXRayValidate"
    seed: 2000
    label_min_max: [0.001, 0.999]
    num_classes: 2
    num_workers: 4
    dataroot: '~/TB_data'

model:
    type: "simple"
    data_dim: 150528 # 224*224*3
    n_input_channels: 3
    n_input_padding: 0
    feature_dim: 4096
    hidden_dim: 4096
    cat_x: True
    cat_y_pred: True
    arch: linear
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True

diffusion:
    beta_schedule: linear  # cosine_anneal, cosine
    beta_start: 0.0001
    beta_end: 0.02
    timesteps: 1000
    vis_step: 100
    num_figs: 10
    include_guidance: True  # concat y_t with aux pred as eps_theta input
    apply_aux_cls: True
    trained_aux_cls_ckpt_path: "./data/classification/pretrained/chest_x_ray_ckpt"
    trained_aux_cls_ckpt_name: None
    # grayscaled
    # seed unknown
#    trained_diffusion_ckpt_path: [ "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_2/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu0_ckpt_best_eph760_acc94.2460.pth",
#                                   "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_3/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu1_ckpt_best_eph990_acc94.2064.pth",
#                                   "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_4/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu2_ckpt_best_eph790_acc95.3175.pth",
#                                   "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_5/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu3_ckpt_best_eph880_acc94.1468.pth",
#                                   "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_6/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu4_ckpt_best_eph650_acc94.2460.pth",
#                                   "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_7/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu5_ckpt_best_eph360_acc96.4683.pth" ]
    # seed 0, 9, 10
    trained_diffusion_ckpt_path: [ [ "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_96/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu0_ckpt_best_eph60_acc98.8571.pth",
                                     "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_97/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu1_ckpt_best_eph60_acc99.5714.pth",
                                     "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_98/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu2_ckpt_best_eph60_acc99.7143.pth",
                                     "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_99/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu3_ckpt_best_eph50_acc99.7143.pth",
                                     "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_100/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu4_ckpt_best_eph40_acc99.7143.pth",
                                     "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_101/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu-1_ckpt_best_eph50_acc99.4286.pth" ],
                                   [ "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_102/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu0_ckpt_best_eph110_acc98.7143.pth",
                                     "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_103/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu1_ckpt_best_eph290_acc99.7143.pth",
                                     "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_104/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu2_ckpt_best_eph370_acc99.5714.pth",
                                     "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_105/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu3_ckpt_best_eph40_acc99.8571.pth",
                                     "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_106/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu4_ckpt_best_eph40_acc99.4286.pth",
                                     "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_107/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu-1_ckpt_best_eph50_acc99.4286.pth" ],
                                   [ "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_108/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu0_ckpt_best_eph50_acc99.2857.pth",
                                     "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_109/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu1_ckpt_best_eph60_acc99.4286.pth",
                                     "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_110/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu2_ckpt_best_eph60_acc99.7143.pth",
                                     "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_111/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu3_ckpt_best_eph50_acc99.4286.pth",
                                     "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_112/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu4_ckpt_best_eph100_acc99.5714.pth",
                                     "./results/chest_x_ray/card_onehot_conditional_results/1000steps/nn/run_113/f_phi_prior_cat_f_phi/f_phi_supervised/logs/chest_x_ray/split_0/diffu-1_ckpt_best_eph320_acc99.1429.pth" ] ]
    aux_cls:
        arch: sevit
        pre_train: False
        joint_train: False
        n_pretrain_epochs: 10
        logging_interval: 1
        feature_dim: 151296
    granularity: 50

training:
    batch_size: 48 #256
    n_epochs: 1000
    warmup_epochs: 40
    add_t0_loss: False
    n_steps_req_grad: 100
    n_minibatches_add_ce: 20
    n_ce_epochs_warmup: 10
    n_ce_epochs_interval: 50
    n_sanity_check_epochs_freq: 500
    snapshot_freq: 1000000000
    logging_freq: 1200
    validation_freq: 10
    image_folder: 'training_image_samples'

sampling:
    batch_size: 48 #256
    sampling_size: 1000
    last_only: True
    image_folder: 'sampling_image_samples'

testing:
    batch_size: 70 #250
    sampling_size: 1000
    last_only: True
    plot_freq: 200
    image_folder: 'testing_image_samples'
    n_samples: 100
    n_bins: 10
    compute_metric_all_steps: False
    metrics_t: 0
    ttest_alpha: 0.05
    trimmed_mean_range: [0.0, 100.0]
    PICP_range: [2.5, 97.5]
    make_plot: True
    squared_plot: True
    plot_true: True
    plot_gen: True
    fig_size: [8, 5]

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.001
    beta1: 0.9
    amsgrad: False
    eps: 0.00000001
    grad_clip: 1.0
    lr_schedule: True
    min_lr: 0.0

aux_optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.001
    beta1: 0.9
    amsgrad: True
    eps: 0.00000001
    grad_clip: 1.0