data:
    dataset: "ISICSkinCancerValidate"
    seed: 2000
    label_min_max: [0.001, 0.999]
    num_classes: 2
    num_workers: 4
    dataroot: '~/SC_data'

model:
    type: "simple"
    data_dim: 150528 # 224*224*3
    n_input_channels: 3
    n_input_padding: 0
    feature_dim: 4096
    hidden_dim: 4096
    cat_x: True
    cat_y_pred: True
    arch: linear
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True

diffusion:
    beta_schedule: linear  # cosine_anneal, cosine
    beta_start: 0.0001
    beta_end: 0.02
    timesteps: 1000
    vis_step: 100
    num_figs: 10
    include_guidance: True  # concat y_t with aux pred as eps_theta input
    apply_aux_cls: True
    trained_aux_cls_ckpt_path: "./data/classification/pretrained/isic_skin_cancer_ckpt"
    trained_aux_cls_ckpt_name: None
    # grayscaled
    # seed 0, 1000, 4000
#    trained_diffusion_ckpt_path: [["./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_66/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu0_ckpt_best_eph560_acc91.2755.pth",
#                                   "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_67/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu1_ckpt_best_eph550_acc92.2959.pth",
#                                   "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_68/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu2_ckpt_best_eph40_acc92.8571.pth",
#                                   "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_69/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu3_ckpt_best_eph90_acc92.9592.pth",
#                                   "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_70/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu4_ckpt_best_eph120_acc92.4490.pth",
#                                   "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_71/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu-1_ckpt_best_eph120_acc93.1122.pth"],
#                                  ["./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_84/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu0_ckpt_best_eph440_acc90.9184.pth",
#                                   "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_85/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu1_ckpt_best_eph630_acc92.1429.pth",
#                                   "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_86/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu2_ckpt_best_eph180_acc92.6020.pth",
#                                   "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_87/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu3_ckpt_best_eph990_acc93.3163.pth",
#                                   "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_88/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu4_ckpt_best_eph650_acc93.3163.pth",
#                                   "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_89/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu-1_ckpt_best_eph180_acc93.7755.pth"],
#                                  ["./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_90/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu0_ckpt_best_eph800_acc91.2245.pth",
#                                   "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_91/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu1_ckpt_best_eph150_acc91.8367.pth",
#                                   "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_92/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu2_ckpt_best_eph240_acc93.2653.pth",
#                                   "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_93/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu3_ckpt_best_eph730_acc93.2653.pth",
#                                   "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_94/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu4_ckpt_best_eph90_acc93.4184.pth",
#                                   "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_95/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu-1_ckpt_best_eph430_acc93.4694.pth"]]
    # seed 7, 75, 1000
    trained_diffusion_ckpt_path: [ [ "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_114/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu0_ckpt_best_eph690_acc90.9184.pth",
                                     "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_115/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu1_ckpt_best_eph330_acc92.0918.pth",
                                     "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_116/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu2_ckpt_best_eph330_acc92.3469.pth",
                                     "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_117/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu3_ckpt_best_eph330_acc92.7041.pth",
                                     "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_118/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu4_ckpt_best_eph370_acc92.4490.pth",
                                     "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_119/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu-1_ckpt_best_eph560_acc91.8878.pth" ],
        [ "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_120/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu0_ckpt_best_eph490_acc91.1224.pth",
          "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_121/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu1_ckpt_best_eph860_acc92.4490.pth",
          "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_122/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu2_ckpt_best_eph720_acc93.4184.pth",
          "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_123/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu3_ckpt_best_eph90_acc93.5204.pth",
          "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_124/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu4_ckpt_best_eph130_acc93.1633.pth",
          "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_125/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu-1_ckpt_best_eph220_acc94.3367.pth" ],
        [ "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_84/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu0_ckpt_best_eph440_acc90.9184.pth",
          "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_85/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu1_ckpt_best_eph630_acc92.1429.pth",
          "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_86/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu2_ckpt_best_eph180_acc92.6020.pth",
          "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_87/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu3_ckpt_best_eph990_acc93.3163.pth",
          "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_88/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu4_ckpt_best_eph650_acc93.3163.pth",
          "./results/isic_skin_cancer/card_onehot_conditional_results/1000steps/nn/run_89/f_phi_prior_cat_f_phi/f_phi_supervised/logs/isic_skin_cancer/split_0/diffu-1_ckpt_best_eph180_acc93.7755.pth" ] ]
    aux_cls:
        arch: sevit
        pre_train: False
        joint_train: False
        n_pretrain_epochs: 10
        logging_interval: 1
        feature_dim: 151296
    granularity: 50

training:
    batch_size: 48 #256
    n_epochs: 1000
    warmup_epochs: 40
    add_t0_loss: False
    n_steps_req_grad: 100
    n_minibatches_add_ce: 20
    n_ce_epochs_warmup: 10
    n_ce_epochs_interval: 50
    n_sanity_check_epochs_freq: 500
    snapshot_freq: 1000000000
    logging_freq: 1200
    validation_freq: 10
    image_folder: 'training_image_samples'

sampling:
    batch_size: 48 #256
    sampling_size: 1000
    last_only: True
    image_folder: 'sampling_image_samples'

testing:
    batch_size: 70 #250
    sampling_size: 1000
    last_only: True
    plot_freq: 200
    image_folder: 'testing_image_samples'
    n_samples: 100
    n_bins: 10
    compute_metric_all_steps: False
    metrics_t: 0
    ttest_alpha: 0.05
    trimmed_mean_range: [0.0, 100.0]
    PICP_range: [2.5, 97.5]
    make_plot: True
    squared_plot: True
    plot_true: True
    plot_gen: True
    fig_size: [8, 5]

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.001
    beta1: 0.9
    amsgrad: False
    eps: 0.00000001
    grad_clip: 1.0
    lr_schedule: True
    min_lr: 0.0

aux_optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.001
    beta1: 0.9
    amsgrad: True
    eps: 0.00000001
    grad_clip: 1.0